version: '3'
services:
  minio2:
    image: minio/minio:RELEASE.2022-05-03T20-36-08Z
    environment:
      MINIO_ACCESS_KEY: foobar
      MINIO_SECRET_KEY: foobardd
    networks: ["test"]
    command: server /data
    volumes:
      - data2:/data
  minio1:
    image: minio/minio:RELEASE.2022-05-03T20-36-08Z
    environment:
      MINIO_ACCESS_KEY: foobar
      MINIO_SECRET_KEY: foobardd
    networks: ["test"]
    command: server /data
    volumes:
      - data:/data
  tester:
    networks: ["test"]
    build:
      context: .
      dockerfile: Dockerfile.tester
    command: ["true"] # do not start the container when `docker-compose up` is executed

networks:
  test:

volumes:
  data:
  data2:
